version: "3"
services:

## uk based edge caches
## Emulating the Datacenter operating out of London

    uk-edge-envoy:
        ports:
            - '80:80'
            - '443:443'
            - '9901:9901'
        restart: always
        logging:
            options:
                max-size: 1g
        image: warmfusion/evhl-edge:latest
        volumes:
          - ${PWD}/conf/edge/envoy:/etc/envoy
        depends_on:
            - uk-edge-varnish

    uk-edge-varnish:
        restart: always
        # ports:
        #     - '81:6081'
        logging:
            options:
                max-size: 1g
        image: 'warmfusion/varnish:5.2.1-1-stretch'
        command: ["/opt/varnish/start-varnish.sh", "origin", "uk-origin-envoy"]
        volumes:
          - ${PWD}/conf/edge/varnish:/etc/varnish
        depends_on:
            - uk-origin-envoy

## us based edge cache
## Emulating the Cloud based services out of the us

    # us-edge-envoy:
    #     ports:
    #         - '1080:80'
    #         - '1443:443'
    #     restart: always
    #     logging:
    #         options:
    #             max-size: 1g
    #     image: envoyproxy/envoy:latest
    # us-edge-varnish:
    #     restart: always
    #     logging:
    #         options:
    #             max-size: 1g
    #     image: 'warmfusion/varnish:5.2.1-1-stretch'


## uk based origin caches
## Emulating the resilient caches acting as origin caches

    uk-origin-envoy:
        # ports:
        #     - '8080:80'
        restart: always
        logging:
            options:
                max-size: 1g
        image: warmfusion/evhl-origin:latest
        volumes:
          - ${PWD}/conf/origin/envoy:/etc/envoy
        depends_on:
            - uk-origin-varnish

    uk-origin-varnish:
        restart: always
        # ports:
        #     - '8081:6081'
        logging:
            options:
                max-size: 1g
        image: 'warmfusion/varnish:5.2.1-1-stretch'
        command: ["/opt/varnish/start-varnish.sh", "service", "uk-service", "4567"]
        volumes:
          - ${PWD}/conf/origin/varnish:/etc/varnish
        depends_on:
            - uk-service

## uk based origin backend service
## Emulating the services delivering functionality


    uk-service:
        image: warmfusion/evhl-test-app:latest
        ports:
            - '4567:4567'
        restart: always
        logging:
            options:
                max-size: 1g