version: "3.7"
services:

    ## uk based edge caches
## Emulating the Datacenter operating out of London

    uk-edge-envoy:
        restart: always
        image: docker.artifactory.futurenet.com/tjackson02/evha-edge-envoy:master
        depends_on:
            - uk-edge-varnish
        networks:
            - traefik_network
        deploy:
            replicas: 2
            labels:
                - traefik.evha-envoy.port=80
                - traefik.evha-envoy.frontend.rule=Host:evha.swarm.future.net.uk
                - traefik.docker.network=traefik_network
            update_config:
                parallelism: 1
                delay: 20s
                order: start-first
            placement:
                constraints:
                    - node.role == worker # Mandatory line
            restart_policy:
                condition: any

    uk-edge-varnish:
        restart: always
        image: docker.artifactory.futurenet.com/tjackson02/evha-edge-varnish:master
        command: ["/opt/varnish/start-varnish.sh", "origin", "uk-origin-envoy"]
        depends_on:
            - uk-origin-envoy
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 20s
                order: start-first
            placement:
                constraints:
                    - node.role == worker # Mandatory line
            restart_policy:
                condition: any

## uk based origin caches
## Emulating the resilient caches acting as origin caches

    uk-origin-envoy:
        restart: always
        image: docker.artifactory.futurenet.com/tjackson02/evha-origin-envoy:master
        depends_on:
            - uk-origin-varnish
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 20s
                order: start-first
            placement:
                constraints:
                    - node.role == worker # Mandatory line
            restart_policy:
                condition: any

    uk-origin-varnish:
        restart: always
        image: docker.artifactory.futurenet.com/tjackson02/evha-origin-varnish:master
        command: ["/opt/varnish/start-varnish.sh", "service", "uk-service", "4567"]
        depends_on:
            - uk-service
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 20s
                order: start-first
            placement:
                constraints:
                    - node.role == worker # Mandatory line
            restart_policy:
                condition: any

## uk based origin backend service
## Emulating the services delivering functionality


    uk-service:
        image: docker.artifactory.futurenet.com/tjackson02/evha-test-app:master
        restart: always
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 20s
                order: stop-first
            placement:
                constraints:
                    - node.role == worker # Mandatory line
            restart_policy:
                condition: any

networks:
  traefik_network:
    driver: overlay
    external: true
