ARG version
ARG mode

FROM docker.artifactory.futurenet.com/tjackson02/varnish:$version
LABEL name="Varnish $version - EVHA $mode container"

COPY src/varnish /opt/varnish
COPY conf/$mode/varnish /etc/varnish
