all:
    children:
        swarm:
            children:
                core-swarm-masters:
                    children:
                        core-swarm-masters-common:
                            hosts:
                              swarmmastergrey.core.future.net.uk:
                        core-swarm-masters-bootstrap:
                            hosts:
                              core.swarm.deploy: # Used to deploy stacks
                                  ansible_host: swarmmasterviolet.core.future.net.uk # Used to bootstrap the cluster