---
apiVersion: v1
kind: Service
metadata:
  name: uk-edge-envoy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: uk-edge-envoy
  type: LoadBalancer