apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: uk-edge-varnish
  name: uk-edge-varnish
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: uk-edge-varnish
    spec:
      containers:
      - args:
        - /opt/varnish/start-varnish.sh
        - origin
        - tjackson02-evha_uk-origin-envoy
        image: docker.artifactory.futurenet.com/tjackson02/evha-edge-varnish:master
        name: uk-edge-varnish
        resources: {}
      restartPolicy: Always
status: {}
