apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: uk-origin-envoy
  name: uk-origin-envoy
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: uk-origin-envoy
    spec:
      containers:
      - image: docker.artifactory.futurenet.com/tjackson02/evha-origin-envoy:master
        name: uk-origin-envoy
        resources: {}
      restartPolicy: Always
status: {}
